config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items
  resources :bills
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#splash"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :items

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :bills

  validates :name, presence: true
  validates :amount, presence: true, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bills
  has_many :items
  has_one_attached :picture

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name image email password])
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bill, only: %i[show edit update destroy]

  # GET /bills or /bills.json
  def index
    @bills = Bill.all
    @bills = Bill.includes(:items).all.order(created_at: :desc)
  end

  # GET /bills/1 or /bills/1.json
  def show
    @bills = Bill.where(author_id: current_user.id)
    @items = Item.where(bill_id: params[:id]).order(created_at: :desc)
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit; end

  # POST /bills or /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to root_path, notice: 'Categrory was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1 or /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to bill_url(@bill), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1 or /bills/1.json
  def destroy
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bill
    @bill = Bill.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def bill_params
    params.require(:bill).permit(:name, :icon, :author_id)
  end

  def calculate_item_count(bill)
    Item.where(bill_id: bill.id).count
  end

  def calculate_item_amount(bill)
    @items = Item.where(bill_id: bill.id)
    item_amount = 0
    @items.each do |item|
      item_amount += item.amount
    end
    item_amount
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: %i[show edit update destroy]

  # GET /items or /items.json
  def index
    @items = Item.includes(:bill).all
  end

  # GET /items/1 or /items/1.json
  def show; end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit; end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to bill_url(@item.bill_id), notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
    @item = Item.includes(:bill).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def item_params
    params.require(:item).permit(:name, :amount, :author_id, :bill_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.includes(:bills).all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.includes(:bills).find(params[:id])
  end

  def splash
    return unless user_signed_in?

    redirect_to bills_path
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.includes(:categories).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
  def calculate_item_count(bill)
    Item.where(bill_id: bill.id).count
  end

  def calculate_item_amount(bill)
    @items = Item.where(bill_id: bill.id)
    item_amount = 0
    @items.each do |item|
      item_amount += item.amount
    end
    item_amount
  end

  def calculate_total_budget
    @bills.sum { |bill| calculate_item_amount(bill) }
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bills/_bill.html.erb
<div id="<%= dom_id bill %>", class='item-card' >
  <div class='card-section-1'>
    <%= image_tag "#{bill.icon}.png", alt: "category icon", class: 'category-icon' %>
  </div> 
  <p>
    <%= bill.name %>
  </p>

  <p class='card-section-2 small'>
    <%= bill.created_at.strftime("%d %B %Y") %>
  </p>

 <div style='text-align: right; font-weight: bold;'>
    <p>&dollar;&nbsp;<%= calculate_item_amount(bill) %></p>
  </div> 

</div>

app/views/bills/_form.html.erb
<%= form_with(model: bill) do |form| %>
  <% if bill.errors.any? %>
    <div>
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% bill.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <% form.label :name %>
    <%= form.text_field :name, class: 'form-element', placeholder: 'Name' %>
  </div>

  <div>
      <% form.label :icon, style: "display: block" %>
      <%= form.select :icon, ['default', 'family', 'food', 'sports', 'home', 'travel', 'charity', 'school', 'utilty', 'Phone', 'automobile'], { prompt: "Select an icon for the Category" }, class: "form-select input-field prompt" %>
    </div>

  <div>
    <%= form.hidden_field :author_id, value: current_user.id %>
  </div>

  <div style='margin: 12px; '>
    <%= form.submit 'Create Category', class: 'btn btn-submit' %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing bill</h1>

<%= render "form", bill: @bill %>

<br>

<div>
  <%= link_to "Show this bill", @bill %> |
  <%= link_to "Back to bills", bills_path %>
</div>

app/views/bills/index.html.erb
<div class='category-container'>
  <div id="categories">
    <div class='login'>
      <div class= 'bars'>
        <span class= 'bar'></span>
        <span class= 'bar'></span>
        <span class= 'bar'></span>
      </div>
      <h2 class=''>Categories</h2>
      <div>
        <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-primary' %>
      </div>
    </div> 
    <div class='sub-title'>
      <p>Total Expenses</p>

    <p>&dollar;&nbsp;<%= calculate_total_budget %></p> 

    </div>
    <div class='list-container'>
      <% @bills.each do |bill| %>
        <%= link_to bill, class: 'card-link' do %>
          <div class='card-box'>
            <%= render bill %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <%= link_to "New category", new_bill_path, class: 'btn btn-submit' %>
</div>

app/views/bills/new.html.erb
  <div class='login'>
    <%= link_to root_path do %>
      <i class="fa-solid fa-arrow-left fa-2x white"></i>
    <% end %>
    <p style='margin-top: auto; margin-buttom: auto;'>NEW CATEGORY</P>
    <div></div>
    
  </div>

<%= render "form", bill: @bill %>

app/views/bills/show.html.erb
<div class='login'>
    <%= link_to bills_path do %>
      <i class="fa-solid fa-arrow-left fa-2x white"></i>
    <% end %>
    <p style='margin-top: auto; margin-buttom: auto;'>TRANSACTIONS</P>
    <div></div>
    
  </div>

<div class='page-container', style='background-color: white;'>
  <div class='transaction-title'>
    <%= image_tag "#{@bill.icon}.png", alt: "category icon", class: 'category-icon' %>
    <h3 class='text-1'><%= @bill.name %></h3>
  </div> 

  <p class= ''>Details expenses for <%= @bill.name %> so far. <br>
  The total amount for <%= @bill.name %> is found below.</p>
  <hr style='padding: 0; marging: 0 !important;'>
    <div id="items" class='trans-container' >
      <% item_amount = 0 %>
      <% @items.each do |item| %>
        <%= render item %>
        <% item_amount += item.amount %>
      <% end %>
    </div>

  <div class='trans-total'>
    <p style='padding: 0; margin: 0;'>TOTAL AMOUNT</p>
    <p  style='padding: 0; margin: 0;'>&dollar;&nbsp;<%= item_amount %></p>
  </div>
</div>

<div style='margin: 12px;' >
    <%= link_to "ADD A TRANSACTION", new_item_path, class: 'btn btn-submit' %>
</div>

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <% form.label :name %>
    <%= form.text_field :name, class: 'form-element', placeholder: 'Name' %>
  </div>

  <div>
    <% form.label :amount %>
    <%= form.text_field :amount, class: 'form-element', placeholder: 'Amount' %>
  </div>
  
  <div>
    <%= form.hidden_field :author_id, value: current_user.id %>
  </div>

  <div>
    <% @bills = Bill.where(author_id: current_user.id) %>
    <%= form.select :bill_id, options_from_collection_for_select(@bills, :id, :name, params[:bill_id]), { prompt: "Select a Category" }, class: "form-select input-field prompt" %>
  </div>

  <div style='margin: 12px;' >
    <%= form.submit 'Create Transaction', class: 'btn btn-submit' %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>" class='trans-card'>
  <p style='padding: 0; margin: 0;' >
    <strong>Name:</strong>
    <%= item.name %>
  </p>

  <p style='padding: 0; margin: 0; font-size: small;'>
    <strong>Amount:</strong>
    <%= item.amount %>
  </p>

</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<h1>Transactions</h1>

<div id="transactions">
  <% @items.each do |item| %>
    <%= render item %>
    <p>
      <%= link_to "Show this transaction", item %>
    </p>
  <% end %>
</div>

<%= link_to "New transaction", new_item_path %>

app/views/items/new.html.erb
<div class='login'>
    <%= link_to bills_path do %>
      <i class="fa-solid fa-arrow-left fa-2x white"></i>
    <% end %>
    <p style='margin-top: auto; margin-buttom: auto;'>NEW TRANSACTION</P>
    <div></div>
    
  </div>

<%= render "form", item: @item %>

<br>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bill %>

<div>
  <%= link_to "Edit this transaction", edit_transaction_path(@transaction) %> |
  <%= link_to "Back to transactions", transactions_path %>

  <%= button_to "Destroy this transaction", @transaction, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XpensTrackr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application",  "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="app">
      <div class="app-container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>

app/views/users/splash.html.erb
<div class='splash-page'>
  <h1 class='splash-title'>XpenseTrackr</h1>
  <div class='login-signup'>
    <%= link_to 'LOG IN', new_user_session_path, class: 'splash-login btn btn-primary' %>
    <%= link_to 'SIGN UP', new_user_registration_path, class: 'splash-signup btn btn-secondary' %>
  </div>
</div>